version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=LPyach123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis
    ports:
      - '6379:6379'

  app:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8001:8000'

volumes:
  pg_data:

